version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    restart: on-failure:3

  web:
    build:
      context: ./
    command: converter-api
    expose:
      - 8000
    restart: on-failure:3


  redis:
    image: redis:alpine
    restart: on-failure:3
